"""
Django settings for ecommerce_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os # Asegúrate de que esta línea esté aquí y no duplicada

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(a7#((oegwu_g$!vii%7a&3y)yacr+yj6v6_lbyeg(m)tu!75_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # CAMBIO: Asegúrate que sea False para producción

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend'] # CAMBIO: 'backend' es el nombre del servicio Docker
# IMPORTANTE: Cuando despliegues, añadirás aquí el dominio de tu aplicación (ej. your-app.onrender.com)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   # ¡AÑADE ESTA LÍNEA!
    'corsheaders',      # ¡AÑADE ESTA LÍNEA!
    'products',         # Tu aplicación de productos
    'orders',           # Tu aplicación de órdenes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # ¡AÑADE ESTA LÍNEA AQUÍ!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',        # Nombre de la DB dentro del contenedor de Postgres
        'USER': 'postgres',        # Usuario por defecto de Postgres
        'PASSWORD': 'mysecretpassword', # La contraseña que usaremos en docker-compose
        'HOST': 'db',              # ¡Importante! Este es el nombre del servicio de la DB en docker-compose
        'PORT': '5432',            # Puerto por defecto de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' # <--- ¡CON LA BARRA INICIAL!
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected') # Nombre explícito de la carpeta

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Puerto por defecto de React en desarrollo
    "http://127.0.0.1:3000",
    # IMPORTANTE: Agrega aquí la URL de tu frontend cuando lo despliegues (ej. https://your-frontend.onrender.com)
]
CORS_ALLOW_ALL_ORIGINS = True # Durante desarrollo puedes puedes quitarlo en prod.
# Añade esto al final del archivo para servir estáticos en desarrollo si DEBUG=True
